<?php

return [
     0 => ['author' => 'Oscar Wilde', 'quote' => 'Be yourself; everyone else is already taken.'],
     1 => ['author' => 'William W. Purkey', 'quote' => "You've gotta dance like there's nobody watching, Love like you'll never be hurt, Sing like there's nobody listening, And live like it's heaven on earth."],
     2 => ['author' => 'Mahatma Gandhi', 'quote' => 'Be the change that you wish to see in the world.'],
     3 => ['author' => 'Eleanor Roosevelt', 'quote' => 'No one can make you feel inferior without your consent.'],
     4 => ['author' => 'Mahatma Gandhi', 'quote' => 'Live as if you were to die tomorrow. Learn as if you were to live forever.'],
     5 => ['author' => 'Martin Luther King Jr', 'quote' => 'Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.'],
     6 => ['author' => 'Friedrich Nietzsche', 'quote' => 'Without music, life would be a mistake'],
     7 => ['author' => 'Stephen Chbosky', 'quote' => 'We accept the love we think we deserve'],
     8 => ['author' => 'Marilyn Monroe', 'quote' => "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring"],
     9 => ['author' => 'Albert Einstein', 'quote' => 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.'],
    10 => ['author' => 'Oscar Wilde', 'quote' => 'We are all in the gutter, but some of us are looking at the stars.'],
    11 => ['author' => 'Neil Gaiman', 'quote' => 'Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.'],
    12 => ['author' => 'Bill Keane', 'quote' => 'Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.'],
    13 => ['author' => 'Thomas A. Edison', 'quote' => "I have not failed. I've just found 10,000 ways that won't work."],
    14 => ['author' => 'Elie Wiesel', 'quote' => "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference."],
    15 => ['author' => 'Albert Einstein', 'quote' => 'I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.'],
    16 => ['author' => 'Dr. Seuss', 'quote' => "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You're on your own. And you know what you know. And YOU are the one who'll decide where to go..."],
    17 => ['author' => 'George Eliot', 'quote' => 'It is never too late to be what you might have been.'],
    18 => ['author' => 'Marilyn Monroe', 'quote' => "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about."],
    19 => ['author' => 'Maya Angelou', 'quote' => 'There is no greater agony than bearing an untold story inside you.'],
    20 => ['author' => 'Pablo Picasso', 'quote' => 'Everythign you can imagine is real.'],
    21 => ['author' => 'C.S. Lewis', 'quote' => 'You can never get a cup of tea large enough or a book long enough to suit me.'],
    22 => ['author' => 'J.K. Rowling', 'quote' => 'To the well-organized mind, death is but the next great adventure.'],
    23 => ['author' => ' George Bernard Shaw', 'quote' => "Life isn't about finding yourself. Life is about creating yourself."],
    24 => ['author' => 'Theodore Roosevelt', 'quote' => 'Do what you can, with what you have, where you are.'],
    25 => ['author' => 'Shel Silverstein', 'quote' => "Listen to the mustn'ts, child. Listen to the don'ts. Listen to the shouldn'ts, the impossibles, the won'ts. Listen to the never haves, then listen close to me... Anything can happen, child. Anything can be."],
    26 => ['author' => 'Winston S. Churchill', 'quote' => 'Success is not final, failure is not fatal: it is the courage to continue that counts'],
    27 => ['author' => 'Stephen Chbosky', 'quote' => 'So, this is my life. And I want you to know that I am both happy and sad and Im still trying to figure out how that could be.'],
    28 => ['author' => 'John Lennon', 'quote' => "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one."],
    29 => ['author' => 'Marianne Williamson', 'quote' => "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, 'Who am I to be brilliant, gorgeous, talented, fabulous?' Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won't feel insecure around you. We are all meant to shine, as children do. We were born to make manifest the glory of God that is within us. It's not just in some of us; it's in everyone. And as we let our own light shine, we unconsciously give other people permission to do the same. As we are liberated from our own fear, our presence automatically liberates others."],
    30 => ['author' => 'Lewis Carroll', 'quote' => "It’s no use going back to yesterday, because I was a different person then."],
    31 => ['author' => 'Maya Angelou', 'quote' => "What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it. Don't complain."],
    32 => ['author' => 'Paulo Coelho', 'quote' => 'Its the possibility of having a dream come true that makes life interesting.'],
    33 => ['author' => 'Dr. Seuss', 'quote' => "A person's a person, no matter how small."],
    34 => ['author' => 'Bob Marley', 'quote' => "He’s not perfect. You aren’t either, and the two of you will never be perfect. But if he can make you laugh at least once, causes you to think twice, and if he admits to being human and making mistakes, hold onto him and give him the most you can. He isn’t going to quote poetry, he’s not thinking about you every moment, but he will give you a part of him that he knows you could break. Don’t hurt him, don’t change him, and don’t expect for more than he can give. Don’t analyze. Smile when he makes you happy, yell when he makes you mad, and miss him when he’s not there. Love hard when there is love to be had. Because perfect guys don’t exist, but there’s always one guy that is perfect for you."],
    35 => ['author' => 'Henri Nouwen', 'quote' => 'When we honestly ask ourselves which person in our lives mean the most to us, we often find that it is those who, instead of giving advice, solutions, or cures, have chosen rather to share our pain and touch our wounds with a warm and tender hand. The friend who can be silent with us in a moment of despair or confusion, who can stay with us in an hour of grief and bereavement, who can tolerate not knowing, not curing, not healing and face with us the reality of our powerlessness, that is a friend who cares.'],
    36 => ['author' => 'Nicholas Sparks', 'quote' => "You can't live your life for other people. You've got to do what's right for you, even if it hurts some people you love."],
    37 => ['author' => 'Laurel Thatcher Ulrich', 'quote' => 'Well-behaved women seldom make history.'],
    38 => ['author' => 'Mahatma Gandhi', 'quote' => 'When I despair, I remember that all through history the way of truth and love have always won. There have been tyrants and murderers, and for a time, they can seem invincible, but in the end, they always fall. Think of it--always.'],
    39 => ['author' => 'F. Scott Fitzgerald', 'quote' => 'So we beat on, boats against the current, borne back ceaselessly into the past.'],
    40 => ['author' => 'Audrey Hepburn', 'quote' => "Nothing is impossible, the word itself says 'I'm possible'!”"]
];

?>
